file(STRINGS "${CMAKE_SOURCE_DIR}/APP_METADATA" _metadata_lines)
foreach(_line IN LISTS _metadata_lines)
  if(_line MATCHES "^([A-Z_]+)=(.+)$")
    set(${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
  endif()
endforeach()

if(EXISTS "${CMAKE_SOURCE_DIR}/SECRETS")
  file(STRINGS "${CMAKE_SOURCE_DIR}/SECRETS" _secrets_lines)
  foreach(_line IN LISTS _secrets_lines)
    if(_line MATCHES "^([A-Z_]+)=(.+)$")
      set(${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    endif()
  endforeach()
endif()
